"""Initial migration

Revision ID: 673a4053aa3b
Revises: 
Create Date: 2025-11-17 19:22:56.375906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673a4053aa3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('buyer_tenant_id', sa.Integer(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Integer(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('logistics_tenant_id', sa.Integer(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('received_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logistics_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['received_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_tenant_id'), ['buyer_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_supplier_tenant_id'), ['supplier_tenant_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('source_tenant_id', sa.Integer(), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_inventory_item_id'), ['inventory_item_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.alter_column('generic_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('brand_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('approval_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('dosage_form',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('specification',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=160),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('prescription_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=160),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('unified_social_credit_code',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=40),
               nullable=False)
        batch_op.alter_column('legal_representative',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               nullable=False)
        batch_op.alter_column('contact_person',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               nullable=False)
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               nullable=False)
        batch_op.alter_column('contact_email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('business_scope',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('business_scope',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('contact_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('contact_person',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('legal_representative',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('unified_social_credit_code',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=18),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.alter_column('prescription_type',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('specification',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('dosage_form',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('approval_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('brand_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('generic_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_inventory_item_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_supplier_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_tenant_id'))

    op.drop_table('orders')
    # ### end Alembic commands ###
